-- Migration: B1 + B3 — Baseline WBS Allocations & RAB-WBS Link Mapping Status
-- Date: 2026-05-30
--
-- B1: Add wbs_allocations column to rab_baselines.
--   Stores a snapshot of the WBS budget allocation map at the time of freeze.
--   Shape: { [wbsItemId]: allocatedBudget (IDR) }
--   Immutable reference for EVM PV calculation — not affected by later RAB edits.
--
-- B3: Add mapping_status and mapping_confidence to rab_wbs_links.
--   Distinguishes auto-generated fuzzy links from manually reviewed/confirmed ones.
--   mapping_status: 'auto' | 'reviewed' | 'manual' | 'rejected'
--   mapping_confidence: 0–100 (certainty score of auto-mapping; 100 for manual links)

-- ─── B1: rab_baselines ───────────────────────────────────────────────────────

ALTER TABLE rab_baselines
  ADD COLUMN IF NOT EXISTS wbs_allocations jsonb NOT NULL DEFAULT '{}';

COMMENT ON COLUMN rab_baselines.wbs_allocations IS
  'Frozen WBS budget allocation map at baseline freeze time. Key = wbs_item_id, Value = allocated budget (IDR, including parent rollup). Used as PV basis for EVM — immutable after freeze.';

-- ─── B3: rab_wbs_links ───────────────────────────────────────────────────────

ALTER TABLE rab_wbs_links
  ADD COLUMN IF NOT EXISTS mapping_status text NOT NULL DEFAULT 'manual'
    CHECK (mapping_status IN ('auto', 'reviewed', 'manual', 'rejected'));

ALTER TABLE rab_wbs_links
  ADD COLUMN IF NOT EXISTS mapping_confidence numeric NOT NULL DEFAULT 100
    CHECK (mapping_confidence >= 0 AND mapping_confidence <= 100);

COMMENT ON COLUMN rab_wbs_links.mapping_status IS
  'Origin and review state of this RAB-WBS link. auto = generated by fuzzy match / schedule generator (needs review). reviewed = confirmed by user. manual = created directly by user. rejected = auto-link dismissed.';

COMMENT ON COLUMN rab_wbs_links.mapping_confidence IS
  'Confidence score (0–100) of auto-generated links. Manual links default to 100. Used to surface low-confidence mappings for review.';
